apiVersion: v1
kind: Pod
metadata:
  name: test-pod-secure
  namespace: opennebula-demo
spec:
  restartPolicy: Never
  containers:
    - name: hello-world-secure
      image: hello-world
      securityContext:
        # 1. Disallow privilege escalation
        allowPrivilegeEscalation: false
        # 2. Drop all Linux capabilities
        capabilities:
          drop:
            - "ALL"
        # 3. Ensure the container runs as a non-root user
        runAsNonRoot: true
        # 4. Specify a non-zero user ID to run as
        runAsUser: 1000
        # 5. Use the default, secure seccomp profile
        seccompProfile:
          type: "RuntimeDefault"
